# This is a basic workflow to help you get started with Actions

name: Netlify Builds

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main, yaml ]
  pull_request:
    branches: [ main, yaml ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Development 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      name: "Checkout Source Code"
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        
    # This creates a new env file
    - name: Create dotenv
      uses: iamsauravsharma/create-dotenv@v1.2.1
      with:
          env-prefix: 'ENV_KEY_'
      env:
          ENV_KEY_API_KEY: ${{ secrets.GATSBY_TEST }}
          ENV_KEY_GATSBY_APIKEY: ${{ secrets.GATSBY_APIKEY }}
          ENV_KEY_GATSBY_AUTHDOMAIN: ${{ secrets.GATSBY_AUTHDOMAIN }}
          ENV_KEY_GATSBY_PROJECTID: ${{ secrets.GATSBY_PROJECTID }}
          ENV_KEY_GATSBY_STORAGEBUCKET: ${{ secrets.GATSBY_STORAGEBUCKET }}
          ENV_KEY_GATSBY_MESSAGINGSENDERID: ${{ secrets.GATSBY_MESSAGINGSENDERID }}
          ENV_KEY_GATSBY_APPID: ${{ secrets.GATSBY_APPID }}

    # Runs a set of commands using the runners shell
    - name: Build the site
      env:
          API_KEY: ${{ secrets.GATSBY_TEST }}
          GATSBY_APIKEY: ${{ secrets.GATSBY_APIKEY }}
          GATSBY_AUTHDOMAIN: ${{ secrets.GATSBY_AUTHDOMAIN }}
          GATSBY_PROJECTID: ${{ secrets.GATSBY_PROJECTID }}
          GATSBY_STORAGEBUCKET: ${{ secrets.GATSBY_STORAGEBUCKET }}
          GATSBY_MESSAGINGSENDERID: ${{ secrets.GATSBY_MESSAGINGSENDERID }}
          GATSBY_APPID: ${{ secrets.GATSBY_APPID }}
      run: |
        yarn install --production
        yarn build
      
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2.3
      with:
          publish-dir: './public'
          production-branch: main
          deploy-message: '${{ github.event.head_commit.message }}'
      env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
